### ISSUE TITLE
Organize code as libraries/modular

### ISSUE THREAD

**Issue by Lennie** [RaSan147/pyrobox#72]
The way I see it, you've now got duplicate code in the repository. With the 'main program' and classes it depends on in the same file, but multiple times.

My guess is this is for distribution reasons (maybe even start up time) ?: so you can download a single file and run it. I've done this myself in the past, so I get why you'd want to do it.

Would it be an idea to organize things in such a way that you can have a script that builds that one file from separate files, maybe based on a specification file to only have the features you want ? And then include at least one ready build file in the Git repo, so you'd always have a single file ready for distribution.

**Comment by RaSan147** [comment]
well, its no longer a single file (yes it was few updates ago)
now i'm distributing each updates via pip
this isn't js or node so that you can build it in a single file and share. Standard python package build requires multiple files.

**dev-src folder**: where the python and html (web view) are separately updated (for the ease  of dev.
**src**: where after development files are place in 1 file (manually, because there are many left over test lines in dev-src files, so can't use any build.py yet. Sorry)
  - pyroboxCore.py: the server handler I made for use (like django  and flask)
  - server.py: the file that handles the IO
  - __init__.py: to make package accessible via import
  - __main__.py: the reason you can call youtube_dl via shell without actually running python

So all these files are necessary.
if you want to try, install via `pip install pyrobox`
also https://github.com/RaSan147/pyrobox/releases

**Comment by RaSan147** [comment]
https://github.com/RaSan147/pyrobox/releases/tag/v0.5

this was the last time i made single file (gets messy when things gets large)

**Comment by RaSan147** [comment]
oh my bad (english not 1st language)
maybe you are talking about same class or functions exist multiple times?
well, because i'm doing some performance test and thus made multiple similar things (and yes it worked)
i'll clean up soon, thanks for the headsup

**Comment by RaSan147** [comment]
well most of the functions depend on each other and share variables (config stuffs)
so it'd take time if i try to separate these things. 😅

**Comment by RaSan147** [comment]
i'll fix it today

**Comment by RaSan147** [comment]
the only issue keeping me away from doing so is relative import issue. Packages use relative import
`from .exceptions import LimitExceed`
but in dev env
`ImportError: attempted relative import with no known parent package`

its kinda painful to update them every time. So made it one file

**Comment by RaSan147** [comment]
okk i tried and i'm retreating, big mistake
most of the data is entangled with each other and and untieing them made a huge mess, i'm leaving this issue open

if i have more time and a clear mind and ofcourse more EXP, i'll retry

**Comment by RaSan147** [comment]
@Lennie  I tried my best (can do better with a little more time)

**Comment by RaSan147** [comment]
Re-opening the issue with the hope of making a merge script, download one file and you are good to go. Hopefully will bring it in V1.
